### ISSUE TITLE
Inline quotation includes the closest following char

### ISSUE THREAD

**Issue by essepuntato** [rash-framework/raje-app#13]
In a sentence already written, when one try to add an inline quotation in the middle of it, the character following the closing " is skipped if I move the cursor on the write.

![inline-quotation](https://user-images.githubusercontent.com/3869247/32387723-adf7ed16-c0c5-11e7-9984-0424e596c201.gif)

**Comment by gspinaci** [comment]
A ZERO_SPACE char is added right after the inline_quote.

Untile the user remove it, this behaviour is ok.

Next idea: Implement #31
