### ISSUE TITLE
Footnote

### ISSUE THREAD

**Issue by essepuntato** [rash-framework/raje-app#20]
If I remove a footnote from the list in the end of the paper, and that is the only footnote specified, both the special footnote section and the inline superscript pointer to the footnote must be automatically removed.

**Comment by gspinaci** [comment]
Actual behaviour:
When **the footnote section is removed**, all references to footnotes are replaced with the red error "The referenced item doesn't exist".
The footnote section is removed when the only one footnote is removed.
When a footnote is removed, the corresponding reference is replaced.
