### ISSUE TITLE
Char `&#xA0;` in listing

### ISSUE THREAD

**Issue by essepuntato** [rash-framework/raje-app#24]
It seems that `&#xA0;` is used in listing for emulating the space character. This should be avoided and the common space character should be used instead.

<img width="918" alt="schermata 2017-11-04 alle 23 03 27" src="https://user-images.githubusercontent.com/3869247/32409848-6996c77e-c1b4-11e7-9c8d-3810269230b4.png">

**Comment by gspinaci** [comment]
With the commit 7d3837da0afbd80ac586e501721fc0cfd7db483d the paste is changed. Now it paste only the text, so every unicode char is removed

**Comment by essepuntato** [comment]
Now there is a new character there, which is `&#x200B;`.

<img width="727" alt="schermata 2017-11-12 alle 10 30 54" src="https://user-images.githubusercontent.com/3869247/32697609-9d68e1dc-c794-11e7-9845-5e4f63c8fa66.png">

**Comment by essepuntato** [comment]
And, actually, the old char, `&#xA0;` is still present in other elements, such as:

<img width="901" alt="schermata 2017-11-12 alle 10 32 11" src="https://user-images.githubusercontent.com/3869247/32697617-c7bc979e-c794-11e7-8877-69c5972b91ec.png">

**Comment by gspinaci** [comment]
In the commit 232c5f57b3b95cd02d1e7268431ed4a56861dfbb RAJE call the purify event of the module [html-purify](https://www.npmjs.com/package/html-purify).

Every time the document is saved, it's purified before.

**Comment by gspinaci** [comment]
NOTE: This behaviour happens on start/close, when RAJE tries to add/remove the init_core script from the backend
