### ISSUE TITLE
Value outside p in table cells

### ISSUE THREAD

**Issue by essepuntato** [rash-framework/raje-app#25]
In the last column of tables it happens that a value is specified outside the p.

![table](https://user-images.githubusercontent.com/3869247/32409990-739d0bb8-c1b7-11e7-9471-d1539fa8e8d1.gif)

<img width="201" alt="schermata 2017-11-04 alle 23 25 48" src="https://user-images.githubusercontent.com/3869247/32409995-86c1975e-c1b7-11e7-8802-9cf6be384679.png">

**Comment by gspinaci** [comment]
This behaviour happens when you "triple-click" the text inside the cell, or when you drag the selection `CMD+SHIFT+left arrow`?
