### ISSUE TITLE
Break of undo operations after save

### ISSUE THREAD

**Issue by essepuntato** [rash-framework/raje-app#26]
When one save the document, the whole stack of undo operation is lost.

**Comment by gspinaci** [comment]
With the commit 333cd55 the save workflow is different.

The store content is updated with the iframe content after the save event (an async call is sent from the backend).

Any time a change is done, if the iframe content is different from the one stored, an async call notify the backend that some unsaved changes are done.

In this way closing the window the "unsaved changes" dialog is shown
