### ISSUE TITLE
Performance issues with 2.5K word document

### ISSUE THREAD

**Issue by essepuntato** [rash-framework/raje-app#27]
I'm already encounter performance issues with the following document:

Words: 2263
Figures: 2
Tables: 3
Formulas: 0
Listings: 4

At this point, it is necessary (as a priority) to address this aspect ASAP.

**Comment by essepuntato** [comment]
Tried again, and the issue seems a bit less present – maybe something related to my processes previously. I'll remove the priority label from this.

**Comment by gspinaci** [comment]
Duplicate. This issue now is referenced to #12
