### ISSUE TITLE
Removing a selection move the view

### ISSUE THREAD

**Issue by essepuntato** [rash-framework/raje-app#39]
If one selects a bunch of text and then try to delete it with the "<-" key, the view of the document is moved - which is something similar that happens when I add a cross-reference (I've already opened an issue for that).

![select-remove](https://user-images.githubusercontent.com/3869247/32687986-60481326-c6c8-11e7-8225-e206706e20dd.gif)

**Comment by gspinaci** [comment]
This issue seems to be Fixed thank to 6018db6a87c14131cb4d124cad9f66e9fa9d83be
