### ISSUE TITLE
RASH MathML formulas not visualised

### ISSUE THREAD

**Issue by essepuntato** [rash-framework/raje-app#47]
MathML mathematical formulas, inserted by hand, are not visualised correctly in RAJE.

<img width="241" alt="schermata 2017-11-16 alle 11 33 45" src="https://user-images.githubusercontent.com/3869247/32886797-263bd516-cac2-11e7-9d71-08b084efe133.png">

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
   <mstyle displaystyle="true">
     <mn>2</mn>
     <mo>&#x22C5;</mo>
     <msup>
       <mn>10</mn>
       <mn>1834097</mn>
     </msup>
   </mstyle>
 </math>
```

**Comment by gspinaci** [comment]
Fix with commit 76abf82ff592305771b9a99cd95cd51f393fde3c
