### ISSUE TITLE
The new release does not work

### ISSUE THREAD

**Issue by essepuntato** [rash-framework/raje-app#48]
Trying to open the new release will return an error:

<img width="443" alt="schermata 2017-11-17 alle 09 37 27" src="https://user-images.githubusercontent.com/3869247/32938058-371ce596-cb7b-11e7-8fb7-f529d3433f4e.png">

**Comment by gspinaci** [comment]
Fix with the new release [v0.1.10](https://github.com/rash-framework/raje-app/releases/tag/v0.1.10)
