### ISSUE TITLE
Non-XML document

### ISSUE THREAD

**Issue by essepuntato** [rash-framework/raje-app#65]
It is important that the document produced by RAJE is XML-valid. Some of the tags are not actually compliant with it, i.e. `meta`, `link`, and `img`. As a solution, all these elements **must have** the closure tag - either in full (e.g. `<meta></meta>`) or abbreviated form (e.g. `<meta />`).

**Comment by gspinaci** [comment]
The document wasn't XML-valid because the DOCTYPE tag at the very beginning of the file was cut off during the save process. Fix in d0fcf58f2300400df6309378f168c54faf5a8e9f
